# Generated by Django 4.2.9 on 2024-01-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=200)),
                ('habitat', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
