# Generated by Django 4.2.9 on 2024-01-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='description',
            field=models.CharField(default='No description added yet', max_length=500),
        ),
        migrations.AlterField(
            model_name='bird',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
