# Generated by Django 4.2.9 on 2024-01-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_nestingmaterial_alter_feeding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='nesting_materials',
            field=models.ManyToManyField(to='main_app.nestingmaterial'),
        ),
    ]
