# Generated by Django 4.2.9 on 2024-01-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_nestingmaterial_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='nesting_materials',
            new_name='nestingmaterials',
        ),
    ]
